/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sKubernetesPkgApisBatchV2alpha1CronJobList {
}

impl IoK8sKubernetesPkgApisBatchV2alpha1CronJobList {
  pub fn new() -> IoK8sKubernetesPkgApisBatchV2alpha1CronJobList {
    IoK8sKubernetesPkgApisBatchV2alpha1CronJobList {
    }
  }

}



