/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sApiCoreV1NamespaceSpec : NamespaceSpec describes the attributes on a Namespace.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sApiCoreV1NamespaceSpec {
  /// Finalizers is an opaque list of values that must be empty to permanently remove object from storage. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/
  #[serde(rename = "finalizers")]
  finalizers: Option<Vec<String>>
}

impl IoK8sApiCoreV1NamespaceSpec {
  /// NamespaceSpec describes the attributes on a Namespace.
  pub fn new() -> IoK8sApiCoreV1NamespaceSpec {
    IoK8sApiCoreV1NamespaceSpec {
      finalizers: None
    }
  }

  pub fn set_finalizers(&mut self, finalizers: Vec<String>) {
    self.finalizers = Some(finalizers);
  }

  pub fn with_finalizers(mut self, finalizers: Vec<String>) -> IoK8sApiCoreV1NamespaceSpec {
    self.finalizers = Some(finalizers);
    self
  }

  pub fn finalizers(&self) -> Option<&Vec<String>> {
    self.finalizers.as_ref()
  }

  pub fn reset_finalizers(&mut self) {
    self.finalizers = None;
  }

}



