/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sApiCoreV1NodeAffinity : Node affinity is a group of node affinity scheduling rules.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sApiCoreV1NodeAffinity {
  /// The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding \"weight\" to the sum if the node matches the corresponding matchExpressions; the node(s) with the highest sum are the most preferred.
  #[serde(rename = "preferredDuringSchedulingIgnoredDuringExecution")]
  preferred_during_scheduling_ignored_during_execution: Option<Vec<::models::IoK8sApiCoreV1PreferredSchedulingTerm>>,
  #[serde(rename = "requiredDuringSchedulingIgnoredDuringExecution")]
  required_during_scheduling_ignored_during_execution: Option<::models::IoK8sApiCoreV1NodeSelector>
}

impl IoK8sApiCoreV1NodeAffinity {
  /// Node affinity is a group of node affinity scheduling rules.
  pub fn new() -> IoK8sApiCoreV1NodeAffinity {
    IoK8sApiCoreV1NodeAffinity {
      preferred_during_scheduling_ignored_during_execution: None,
      required_during_scheduling_ignored_during_execution: None
    }
  }

  pub fn set_preferred_during_scheduling_ignored_during_execution(&mut self, preferred_during_scheduling_ignored_during_execution: Vec<::models::IoK8sApiCoreV1PreferredSchedulingTerm>) {
    self.preferred_during_scheduling_ignored_during_execution = Some(preferred_during_scheduling_ignored_during_execution);
  }

  pub fn with_preferred_during_scheduling_ignored_during_execution(mut self, preferred_during_scheduling_ignored_during_execution: Vec<::models::IoK8sApiCoreV1PreferredSchedulingTerm>) -> IoK8sApiCoreV1NodeAffinity {
    self.preferred_during_scheduling_ignored_during_execution = Some(preferred_during_scheduling_ignored_during_execution);
    self
  }

  pub fn preferred_during_scheduling_ignored_during_execution(&self) -> Option<&Vec<::models::IoK8sApiCoreV1PreferredSchedulingTerm>> {
    self.preferred_during_scheduling_ignored_during_execution.as_ref()
  }

  pub fn reset_preferred_during_scheduling_ignored_during_execution(&mut self) {
    self.preferred_during_scheduling_ignored_during_execution = None;
  }

  pub fn set_required_during_scheduling_ignored_during_execution(&mut self, required_during_scheduling_ignored_during_execution: ::models::IoK8sApiCoreV1NodeSelector) {
    self.required_during_scheduling_ignored_during_execution = Some(required_during_scheduling_ignored_during_execution);
  }

  pub fn with_required_during_scheduling_ignored_during_execution(mut self, required_during_scheduling_ignored_during_execution: ::models::IoK8sApiCoreV1NodeSelector) -> IoK8sApiCoreV1NodeAffinity {
    self.required_during_scheduling_ignored_during_execution = Some(required_during_scheduling_ignored_during_execution);
    self
  }

  pub fn required_during_scheduling_ignored_during_execution(&self) -> Option<&::models::IoK8sApiCoreV1NodeSelector> {
    self.required_during_scheduling_ignored_during_execution.as_ref()
  }

  pub fn reset_required_during_scheduling_ignored_during_execution(&mut self) {
    self.required_during_scheduling_ignored_during_execution = None;
  }

}



