/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sApiCoreV1DownwardApiVolumeSource : DownwardAPIVolumeSource represents a volume containing downward API info. Downward API volumes support ownership management and SELinux relabeling.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sApiCoreV1DownwardApiVolumeSource {
  /// Optional: mode bits to use on created files by default. Must be a value between 0 and 0777. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
  #[serde(rename = "defaultMode")]
  default_mode: Option<i32>,
  /// Items is a list of downward API volume file
  #[serde(rename = "items")]
  items: Option<Vec<::models::IoK8sApiCoreV1DownwardApiVolumeFile>>
}

impl IoK8sApiCoreV1DownwardApiVolumeSource {
  /// DownwardAPIVolumeSource represents a volume containing downward API info. Downward API volumes support ownership management and SELinux relabeling.
  pub fn new() -> IoK8sApiCoreV1DownwardApiVolumeSource {
    IoK8sApiCoreV1DownwardApiVolumeSource {
      default_mode: None,
      items: None
    }
  }

  pub fn set_default_mode(&mut self, default_mode: i32) {
    self.default_mode = Some(default_mode);
  }

  pub fn with_default_mode(mut self, default_mode: i32) -> IoK8sApiCoreV1DownwardApiVolumeSource {
    self.default_mode = Some(default_mode);
    self
  }

  pub fn default_mode(&self) -> Option<&i32> {
    self.default_mode.as_ref()
  }

  pub fn reset_default_mode(&mut self) {
    self.default_mode = None;
  }

  pub fn set_items(&mut self, items: Vec<::models::IoK8sApiCoreV1DownwardApiVolumeFile>) {
    self.items = Some(items);
  }

  pub fn with_items(mut self, items: Vec<::models::IoK8sApiCoreV1DownwardApiVolumeFile>) -> IoK8sApiCoreV1DownwardApiVolumeSource {
    self.items = Some(items);
    self
  }

  pub fn items(&self) -> Option<&Vec<::models::IoK8sApiCoreV1DownwardApiVolumeFile>> {
    self.items.as_ref()
  }

  pub fn reset_items(&mut self) {
    self.items = None;
  }

}



