/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sApiCoreV1Toleration : The pod this Toleration is attached to tolerates any taint that matches the triple <key,value,effect> using the matching operator <operator>.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sApiCoreV1Toleration {
  /// Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute.
  #[serde(rename = "effect")]
  effect: Option<String>,
  /// Key is the taint key that the toleration applies to. Empty means match all taint keys. If the key is empty, operator must be Exists; this combination means to match all values and all keys.
  #[serde(rename = "key")]
  key: Option<String>,
  /// Operator represents a key's relationship to the value. Valid operators are Exists and Equal. Defaults to Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category.
  #[serde(rename = "operator")]
  operator: Option<String>,
  /// TolerationSeconds represents the period of time the toleration (which must be of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system.
  #[serde(rename = "tolerationSeconds")]
  toleration_seconds: Option<i64>,
  /// Value is the taint value the toleration matches to. If the operator is Exists, the value should be empty, otherwise just a regular string.
  #[serde(rename = "value")]
  value: Option<String>
}

impl IoK8sApiCoreV1Toleration {
  /// The pod this Toleration is attached to tolerates any taint that matches the triple <key,value,effect> using the matching operator <operator>.
  pub fn new() -> IoK8sApiCoreV1Toleration {
    IoK8sApiCoreV1Toleration {
      effect: None,
      key: None,
      operator: None,
      toleration_seconds: None,
      value: None
    }
  }

  pub fn set_effect(&mut self, effect: String) {
    self.effect = Some(effect);
  }

  pub fn with_effect(mut self, effect: String) -> IoK8sApiCoreV1Toleration {
    self.effect = Some(effect);
    self
  }

  pub fn effect(&self) -> Option<&String> {
    self.effect.as_ref()
  }

  pub fn reset_effect(&mut self) {
    self.effect = None;
  }

  pub fn set_key(&mut self, key: String) {
    self.key = Some(key);
  }

  pub fn with_key(mut self, key: String) -> IoK8sApiCoreV1Toleration {
    self.key = Some(key);
    self
  }

  pub fn key(&self) -> Option<&String> {
    self.key.as_ref()
  }

  pub fn reset_key(&mut self) {
    self.key = None;
  }

  pub fn set_operator(&mut self, operator: String) {
    self.operator = Some(operator);
  }

  pub fn with_operator(mut self, operator: String) -> IoK8sApiCoreV1Toleration {
    self.operator = Some(operator);
    self
  }

  pub fn operator(&self) -> Option<&String> {
    self.operator.as_ref()
  }

  pub fn reset_operator(&mut self) {
    self.operator = None;
  }

  pub fn set_toleration_seconds(&mut self, toleration_seconds: i64) {
    self.toleration_seconds = Some(toleration_seconds);
  }

  pub fn with_toleration_seconds(mut self, toleration_seconds: i64) -> IoK8sApiCoreV1Toleration {
    self.toleration_seconds = Some(toleration_seconds);
    self
  }

  pub fn toleration_seconds(&self) -> Option<&i64> {
    self.toleration_seconds.as_ref()
  }

  pub fn reset_toleration_seconds(&mut self) {
    self.toleration_seconds = None;
  }

  pub fn set_value(&mut self, value: String) {
    self.value = Some(value);
  }

  pub fn with_value(mut self, value: String) -> IoK8sApiCoreV1Toleration {
    self.value = Some(value);
    self
  }

  pub fn value(&self) -> Option<&String> {
    self.value.as_ref()
  }

  pub fn reset_value(&mut self) {
    self.value = None;
  }

}



