/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sApiPolicyV1beta1IdRange : IDRange provides a min/max of an allowed range of IDs.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sApiPolicyV1beta1IdRange {
  /// max is the end of the range, inclusive.
  #[serde(rename = "max")]
  max: i64,
  /// min is the start of the range, inclusive.
  #[serde(rename = "min")]
  min: i64
}

impl IoK8sApiPolicyV1beta1IdRange {
  /// IDRange provides a min/max of an allowed range of IDs.
  pub fn new(max: i64, min: i64) -> IoK8sApiPolicyV1beta1IdRange {
    IoK8sApiPolicyV1beta1IdRange {
      max: max,
      min: min
    }
  }

  pub fn set_max(&mut self, max: i64) {
    self.max = max;
  }

  pub fn with_max(mut self, max: i64) -> IoK8sApiPolicyV1beta1IdRange {
    self.max = max;
    self
  }

  pub fn max(&self) -> &i64 {
    &self.max
  }


  pub fn set_min(&mut self, min: i64) {
    self.min = min;
  }

  pub fn with_min(mut self, min: i64) -> IoK8sApiPolicyV1beta1IdRange {
    self.min = min;
    self
  }

  pub fn min(&self) -> &i64 {
    &self.min
  }


}



