/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sApiAuthorizationV1SelfSubjectRulesReviewSpec {
  /// Namespace to evaluate rules for. Required.
  #[serde(rename = "namespace")]
  namespace: Option<String>
}

impl IoK8sApiAuthorizationV1SelfSubjectRulesReviewSpec {
  pub fn new() -> IoK8sApiAuthorizationV1SelfSubjectRulesReviewSpec {
    IoK8sApiAuthorizationV1SelfSubjectRulesReviewSpec {
      namespace: None
    }
  }

  pub fn set_namespace(&mut self, namespace: String) {
    self.namespace = Some(namespace);
  }

  pub fn with_namespace(mut self, namespace: String) -> IoK8sApiAuthorizationV1SelfSubjectRulesReviewSpec {
    self.namespace = Some(namespace);
    self
  }

  pub fn namespace(&self) -> Option<&String> {
    self.namespace.as_ref()
  }

  pub fn reset_namespace(&mut self) {
    self.namespace = None;
  }

}



