/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sApiCoreV1NodeConfigSource : NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sApiCoreV1NodeConfigSource {
  #[serde(rename = "configMap")]
  config_map: Option<::models::IoK8sApiCoreV1ConfigMapNodeConfigSource>
}

impl IoK8sApiCoreV1NodeConfigSource {
  /// NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil.
  pub fn new() -> IoK8sApiCoreV1NodeConfigSource {
    IoK8sApiCoreV1NodeConfigSource {
      config_map: None
    }
  }

  pub fn set_config_map(&mut self, config_map: ::models::IoK8sApiCoreV1ConfigMapNodeConfigSource) {
    self.config_map = Some(config_map);
  }

  pub fn with_config_map(mut self, config_map: ::models::IoK8sApiCoreV1ConfigMapNodeConfigSource) -> IoK8sApiCoreV1NodeConfigSource {
    self.config_map = Some(config_map);
    self
  }

  pub fn config_map(&self) -> Option<&::models::IoK8sApiCoreV1ConfigMapNodeConfigSource> {
    self.config_map.as_ref()
  }

  pub fn reset_config_map(&mut self) {
    self.config_map = None;
  }

}



