/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sApiAutoscalingV2beta2PodsMetricSource : PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sApiAutoscalingV2beta2PodsMetricSource {
  #[serde(rename = "metric")]
  metric: ::models::IoK8sApiAutoscalingV2beta2MetricIdentifier,
  #[serde(rename = "target")]
  target: ::models::IoK8sApiAutoscalingV2beta2MetricTarget
}

impl IoK8sApiAutoscalingV2beta2PodsMetricSource {
  /// PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.
  pub fn new(metric: ::models::IoK8sApiAutoscalingV2beta2MetricIdentifier, target: ::models::IoK8sApiAutoscalingV2beta2MetricTarget) -> IoK8sApiAutoscalingV2beta2PodsMetricSource {
    IoK8sApiAutoscalingV2beta2PodsMetricSource {
      metric: metric,
      target: target
    }
  }

  pub fn set_metric(&mut self, metric: ::models::IoK8sApiAutoscalingV2beta2MetricIdentifier) {
    self.metric = metric;
  }

  pub fn with_metric(mut self, metric: ::models::IoK8sApiAutoscalingV2beta2MetricIdentifier) -> IoK8sApiAutoscalingV2beta2PodsMetricSource {
    self.metric = metric;
    self
  }

  pub fn metric(&self) -> &::models::IoK8sApiAutoscalingV2beta2MetricIdentifier {
    &self.metric
  }


  pub fn set_target(&mut self, target: ::models::IoK8sApiAutoscalingV2beta2MetricTarget) {
    self.target = target;
  }

  pub fn with_target(mut self, target: ::models::IoK8sApiAutoscalingV2beta2MetricTarget) -> IoK8sApiAutoscalingV2beta2PodsMetricSource {
    self.target = target;
    self
  }

  pub fn target(&self) -> &::models::IoK8sApiAutoscalingV2beta2MetricTarget {
    &self.target
  }


}



