/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JsonSchemaPropsOrBool : JSONSchemaPropsOrBool represents JSONSchemaProps or a boolean value. Defaults to true for the boolean property.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JsonSchemaPropsOrBool {
}

impl IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JsonSchemaPropsOrBool {
  /// JSONSchemaPropsOrBool represents JSONSchemaProps or a boolean value. Defaults to true for the boolean property.
  pub fn new() -> IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JsonSchemaPropsOrBool {
    IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JsonSchemaPropsOrBool {
    }
  }

}



