/* 
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.13.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoK8sApiAuthenticationV1beta1TokenReviewSpec : TokenReviewSpec is a description of the token authentication request.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IoK8sApiAuthenticationV1beta1TokenReviewSpec {
  /// Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver.
  #[serde(rename = "audiences")]
  audiences: Option<Vec<String>>,
  /// Token is the opaque bearer token.
  #[serde(rename = "token")]
  token: Option<String>
}

impl IoK8sApiAuthenticationV1beta1TokenReviewSpec {
  /// TokenReviewSpec is a description of the token authentication request.
  pub fn new() -> IoK8sApiAuthenticationV1beta1TokenReviewSpec {
    IoK8sApiAuthenticationV1beta1TokenReviewSpec {
      audiences: None,
      token: None
    }
  }

  pub fn set_audiences(&mut self, audiences: Vec<String>) {
    self.audiences = Some(audiences);
  }

  pub fn with_audiences(mut self, audiences: Vec<String>) -> IoK8sApiAuthenticationV1beta1TokenReviewSpec {
    self.audiences = Some(audiences);
    self
  }

  pub fn audiences(&self) -> Option<&Vec<String>> {
    self.audiences.as_ref()
  }

  pub fn reset_audiences(&mut self) {
    self.audiences = None;
  }

  pub fn set_token(&mut self, token: String) {
    self.token = Some(token);
  }

  pub fn with_token(mut self, token: String) -> IoK8sApiAuthenticationV1beta1TokenReviewSpec {
    self.token = Some(token);
    self
  }

  pub fn token(&self) -> Option<&String> {
    self.token.as_ref()
  }

  pub fn reset_token(&mut self) {
    self.token = None;
  }

}



